[package]
name = "advent-of-code2020"
version = "0.1.0"
authors = ["Michael Stengel <Mike.Stengel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6"
cached = "0.22.0"
